name: Build and deploy to preview

on:
  repository_dispatch:
    types: dev-deploy
    branches:
      - test # stop this action
  push:
    branches:
      - test # stop this action
  workflow_dispatch:

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'preview'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 6

      - name: update submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm get store)" >> $GITHUB_OUTPUT

      - name: Caching pnpm
        uses: actions/cache@v3
        id: pnpm-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ hashFiles('pnpm.lock') }}
            ${{ runner.os }}-pnpm-

      #       - name: Caching Gatsby
      #         id: gatsby-cache-build
      #         uses: actions/cache@v2
      #         with:
      #           path: |
      #             public
      #             .cache
      #           key: ${{ runner.os }}-gatsby-build-preview-${{ github.run_id }}
      #           restore-keys: |
      #             ${{ runner.os }}-gatsby-build-preview

      - name: Installing dependencies
        run: pnpm install

      - name: Building Milvus site
        run: pnpm build
        env:
          MSERVICE_URL: ${{ secrets.MSERVICE_URL }}
          REPO_STATICS_KEY: ${{ secrets.REPO_STATICS_KEY }}
          IS_PREVIEW: preview
      #         env:
      #           GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      #           CI: true

      - name: Sync files
        run: |
          echo ${{ secrets.RSYNC_PASSWORD }} > rsync.pass
          sudo chmod 600 rsync.pass
          sudo chown root rsync.pass
          sudo rsync --password-file=rsync.pass -rDvpzc --delete out/ rsync://${{secrets.PREVIEW_SITE}}
