name: Verify Nginx Conf

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify Nginx configuration
        uses: addnab/docker-run-action@v3
        with:
          image: zilliz/z2:500969b4fa7d576d81da83ad67caef62b42571db-3981
          options: -v ${{ github.workspace }}/scripts/test.conf:/etc/nginx/nginx.conf
          run: |
            if nginx -t -c /etc/nginx/nginx.conf; then
              echo "Nginx configuration is valid."
            else
              echo "Nginx configuration is invalid."
              exit 1
        if: always()
